title: '@fullarray'
email: fullarray
description: >-
  I'm a naturally curious software, IT, and systems engineer. I enjoy finding
  technology-based solutions. In my free time, I like to go to the beach and
  cruise by A1A on the Florida coastline.
baseurl: ''
url: ''
twitter_username: fullarray
github_username: fullarray
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
